colors:
  # Default colors
  primary:
    background: '0x0E1116'
    foreground: '0xD9D7D6'

  # Normal colors
  normal:
    black:   '0x0E1116'
    red:     '0xFF3377'
    green:   '0x7bff67'
    yellow:  '0xFFFF00'
    blue:    '0x61D0FF'
    magenta: '0x8EFBEE'
    cyan:    '0x61D0FF'
    white:   '0xD9D7D6'

  # Bright colors
  bright:
    black:   '0x0C171B'
    red:     '0xF16269'
    green:   '0x101B1F'
    yellow:  '0xEFEFEF'
    blue:    '0x192428'
    magenta: '0x212C30'
    cyan:    '0xE3E1E0'
    white:   '0xEDEBEA'

window:
  # decorations: buttonless
  dynamic_padding: false
  padding:
    x: 14
    y: 10

font:
  # size: 8.75
  size: 11
  # The normal (roman) font face to use.
  normal:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The bold font face
  bold:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: SauceCodePro Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold Italic

# background_opacity: 0.5
scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

env:
  TERM: xterm-256color

key_bindings:
  - { key: C, mods: Alt, action: Copy }
  - { key: V, mods: Alt, action: Paste }
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
