[colors.bright]
black = "0x2E2E2E"  # Adjusted for increased brightness
blue = "0xA3E4FF"  # Bright blue color - increased brightness
cyan = "0x99E6FF"  # Bright cyan color - increased brightness
green = "0xA3FF91"  # Bright green color - increased brightness
magenta = "0xBAA4D9"  # Bright magenta color - increased brightness
red = "0xFF6B8A"  # Bright red color - increased brightness
white = "0xFFFFFF"  # Adjusted white for better contrast
yellow = "0xFFFF99"  # Bright yellow color - increased brightness

[colors.normal]
black = "0x0C141D"  # Terminal background color
blue = "0x61D0FF"  # Unchanged
cyan = "0x8EFBEE"  # Unchanged
green = "0x40CF84"  # Adjusted for readability
magenta = "0xDE4F72"  # Adjusted for better contrast
red = "0xFF3377"  # Unchanged
white = "0xD9D7D6"  # Terminal text color
yellow = "0xFFFF00"  # Unchanged

[colors.primary]
background = "0x0C141D"  # Terminal background color
foreground = "0xD9D7D6"  # Terminal text color

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Bold"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false

[window.padding]
x = 14
y = 10

