keys:
  - &users:
    - &buttars age1thkm674pc4k2znvjavmquvjprej0xj4fpsk82a9ecc5u69d8q4gq59060q
    - &landon-buttars age1ry7vx3wta86009kenncr8fat85h2yqn4wytkapf6fwp6w2naf96q3qzy59
  - &hosts:
    - &buttars-desktop age10w02unkvvka427edd04fk2jtz6axelus6ehhd8axr4rnqvnsrstqd2gqpq
    - &landon-buttars-wgu age15tkxx8e9h29vn9u3rs6y00pty3tjprsrxl6kmp3nvesklz86eqrq5k2yme
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *buttars
          - *buttars-desktop
          - *landon-buttars
          - *landon-buttars-wgu
