lastupdatecheck: 0
recentrepos:
    - /Users/landon.buttars/dev/student-portal
    - /Users/landon.buttars/dev/wgu-core
    - /Users/landon.buttars/dev/wgu-ui
startuppopupversion: 5
customcommandshistory:
    - q
hidecommandlog: false
