#!/bin/sh
# This file contains aliases for terminal commands

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Automatically add sudo command to these applications
for command in mount umount sv su shutdown poweroff reboot ; do
  alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  rsync="rsync -vrPlu" \
  mkd="mkdir -pv" \
  ll="ls -la" \
  dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
  discord="discord -enable-features=UseOzonePlatform -ozone-platform=wayland"


# Colorize commands 
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
  ka="killall" \
  g="git" \
  sdn="shutdown -h now" \
  e="$EDITOR" \
  v="$EDITOR" \
  f="fuck" \
  g="gorilla"
